// flow-typed signature: 0df301cdce1f48104aa57eb7e0341b41
// flow-typed version: <<STUB>>/lang-detector_v^1.0.6/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lang-detector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lang-detector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lang-detector/test/fizzbuzz/fizzbuzz' {
  declare module.exports: any;
}

declare module 'lang-detector/test/site/bundle' {
  declare module.exports: any;
}

declare module 'lang-detector/test/site/main' {
  declare module.exports: any;
}

declare module 'lang-detector/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lang-detector/index' {
  declare module.exports: $Exports<'lang-detector'>;
}
declare module 'lang-detector/index.js' {
  declare module.exports: $Exports<'lang-detector'>;
}
declare module 'lang-detector/test/fizzbuzz/fizzbuzz.js' {
  declare module.exports: $Exports<'lang-detector/test/fizzbuzz/fizzbuzz'>;
}
declare module 'lang-detector/test/site/bundle.js' {
  declare module.exports: $Exports<'lang-detector/test/site/bundle'>;
}
declare module 'lang-detector/test/site/main.js' {
  declare module.exports: $Exports<'lang-detector/test/site/main'>;
}
declare module 'lang-detector/test/test.js' {
  declare module.exports: $Exports<'lang-detector/test/test'>;
}
